export {
  REVIEW_INTERVALS,
  MASTERY_LEVELS,
  DEFAULT_DAILY_LIMIT,
  LEARNING_CONFIG,
  setDailyLimit,
  getDailyLimit,
  type MasteryLevel,
  type IWordProgress,
  type IDictProgress,
  type IDailyRecord,
  WordProgress,
  DictProgress,
  DailyRecord,
  getTodayDate,
  getNextReviewTime,
  updateMasteryLevel,
} from './progress/index'
